name: Validator

on:
  push:
    branches:
    - 'master'

  pull_request:
    branches:
    - 'master'

  merge_group:

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -Dwarnings
  RUST_BACKTRACE: full

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup local rust toolchain
      uses: actions-rust-lang/setup-rust-toolchain@v1

    - name: Print release toolchain rustc version
      run: ./run-with-release-toolchain rustc --version

    - name: Build release
      run: ./run-with-release-toolchain cargo build --release --workspace

    - name: Run the Validator tests
      run: ./run-validator-with-scylla-docker scylladb/scylladb-releng:2025.4.0-dev-0.20250718.d36c9b3119b7-x86_64 target/release/vector-store target/release/vector-search-validator --verbose

